spring:
  profiles:
    active: test
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format-sql: TRUE
    database: h2
  datasource:
    url: jdbc:h2:mem:AccountManaging
    driver-class-name: org.h2.Driver
    username: root
    password: root
  h2:
    console:
      enabled: true
server:
  http2:
    enabled: true
