spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accountManagingDb?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: TRUE
#server:
#  http2:
#    enabled: true
